# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='service',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='serviceapi',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='serviceapi',
            name='modified_by',
        ),
    ]
