# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170424_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapi',
            name='doc_json',
            field=models.TextField(default=b'{}'),
        ),
    ]
