# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170305_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='base_url',
            field=models.CharField(default='localhost:8000/', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceapi',
            name='doc_yaml',
            field=models.TextField(default=b'{}'),
        ),
        migrations.AddField(
            model_name='serviceapi',
            name='endpoint',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='meta',
            field=models.TextField(default=b'{}'),
        ),
        migrations.AlterField(
            model_name='serviceapi',
            name='meta',
            field=models.TextField(default=b'{}'),
        ),
    ]
