# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170311_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceapi',
            name='body_map',
        ),
        migrations.AlterField(
            model_name='serviceapi',
            name='doc_yaml',
            field=models.TextField(default=b''),
        ),
    ]
