# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='body_map',
            new_name='request_map',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='response_map',
            field=models.TextField(default=b'{}'),
        ),
    ]
