# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20170424_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='doc_json',
            field=models.TextField(default=b''),
        ),
    ]
