# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_endpoint_doc_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='doc_json',
            field=models.TextField(default=b'{}'),
        ),
    ]
